### ISSUE TITLE
Extension not showing on mobile

### ISSUE THREAD

**Issue by mken5** [JokerQyou/snextensions#4]
Hi,
Have followed your guidelines installing locally and on netlify but extension is accessible only on desktop app. 
found the solution through activating CORS on Nginx

**Comment by JokerQyou** [comment]
Thank you for your feedback!

This repository already contains necessary headers for Netlify to activate CORS, see [this file](https://github.com/JokerQyou/snextensions/blob/6d5eda1d1cd5f0ca1dfdc7a31900e660b120f577/_headers). If CORS issue still happens when hosting with Netlify, could you please verify that your deploy details contains this block?

<img width="345" alt="图片" src="https://user-images.githubusercontent.com/1465267/90081951-2d3ff380-dd41-11ea-8d20-ee11c9d871c4.png">

As for the selfhosting solution with Nginx, I've updated README to contain the CORS instructions.

**Comment by JokerQyou** [comment]
Close due to inactivity. Please comment and reopen this issue if you have any information to follow up.
