### ISSUE TITLE
How to add these extensions to selfhosted docker image

### ISSUE THREAD

**Issue by BobWs** [JokerQyou/snextensions#6]
Hi,
I’m selfhosting this image https://github.com/arugifa/standardnotes-server-docker and I was 
wondering how to use/install your extensions to work with this selfhosted docker image?

I have looked everywhere but I cannot find the preference for `Extended code`
Is there something I’m missing or not doing the right way?

**Comment by JokerQyou** [comment]
I have not used that docker image, but the `Extended code` preference is easy to find, here's the steps.

![Find "Extensions" on the left bottom area](https://user-images.githubusercontent.com/1465267/90161879-65d5e080-ddc6-11ea-8d8e-65d61b7bb7df.png)

![Now here's the "Extended code" input](https://user-images.githubusercontent.com/1465267/90162069-a9c8e580-ddc6-11ea-9bbc-2bcc50e61011.png)

Also notice that standard note does not work with private window (a.k.a. incognite window), because it has to store your notes in local database.

**Comment by BobWs** [comment]
Thanks for replying and explaining but I see the extensions button but I cannot do anything it isn’t clickable. And via the desktop app or the iOS app I don’t see any extensions button at all.
 
![961187DE-0131-4340-97BC-1E6150BFC926](https://user-images.githubusercontent.com/5485820/90250059-c5ba9e80-de3b-11ea-8030-db22b1672f55.jpeg)

Is this maybe a bug in the Docker version?

**Comment by BobWs** [comment]
Found it!

The Docker selfhost web version https://github.com/arugifa/standardnotes-web-docker cannot add extensions I think something is wrong with the image. But when I login via app.standardnotes.org to my selfhost standardnotes server I see the same thing you mentioned and I can add the extended code. The extensions are now working with my selfhost server. 

Now I only need to figure out how to selfhost the extensions With Docker.

**Comment by JokerQyou** [comment]
Glad you find it out! It should be relatively easy to host static files with Nginx or Caddy inside docker, checkout the documentation on their official docker hub page to get started. PRs are welcome.
